version: "2"
services:
    db:
        image: mongo:latest
        restart: always
        volumes:
            - ./database:/data/db:rw

    node:
        build: .docker
        volumes:
            - .:/src:rw
        links:
            - "db:mongo"
        ports:
            - "3000:3000"
        #command: "pm2 start server/index.js --name=iot-server --no-daemon"
        depends_on:
            - db
        restart: always