#!/bin/bash -e
echo "---------------------------------------------------"
echo "remote changes"
echo "---------------------------------------------------"
git fetch origin develop
git log HEAD..origin/develop

echo "---------------------------------------------------"
echo "current revision"
echo "---------------------------------------------------"
git rev-list HEAD --count

echo "---------------------------------------------------"
echo "head revision"
echo "---------------------------------------------------"
git rev-list origin/develop --count

echo "---------------------------------------------------"
echo "stopping service iot-server"
echo "---------------------------------------------------"
pm2 stop iot-server

echo "---------------------------------------------------"
echo "in directory"
echo "---------------------------------------------------"
pwd

echo "---------------------------------------------------"
echo "deleting old staging dir"
echo "---------------------------------------------------"
rm -rf staging_dir

echo "---------------------------------------------------"
echo "cloning current repo"
echo "---------------------------------------------------"
git clone https://github.com/d89/IoT-server.git staging_dir
chmod +x staging_dir/update

echo "---------------------------------------------------"
echo "making live"
echo "---------------------------------------------------"
rsync -Ea staging_dir/ .

echo "---------------------------------------------------"
echo "installing node modules"
echo "---------------------------------------------------"
npm install

echo "---------------------------------------------------"
echo "restarting service iot-server"
echo "---------------------------------------------------"
pm2 start iot-server

echo "---------------------------------------------------"
echo "update successfully done"
echo "---------------------------------------------------"